### PR TITLE
fix(adapters): implement deduplicateErrors in domain_to_syft (#728)

### LINKED ISSUE #728: fix(adapters): implement deduplicateErrors helper in domain_to_syf
### Description
In `adapters/v1/domain_to_syft.go:72-78`, `warnConversionErrors` calls `deduplicateErrors`:

```go
func warnConversionErrors[T any](converted []T, errors []error) []T {
	errorMessages := deduplicateErrors(errors)
	for _, msg := range errorMessages {
		logger.L().Warning("SBOM conversion error", helpers.String("error", msg))
	}
	return converted
}
```

However, `deduplicateErrors` is undefined anywhere in the repository, causing `go vet ./...` and compilation to fail:

```text
adapters/v1/domain_to_syft.go:73:19: undefined: deduplicateErrors
```

### Impact
Packages importing or analyzing `adapters/v1` encounter build and static analysis failures when converting domain SBOM representations to Syft structures.

### Expected Behavior
`deduplicateErrors` should be implemented to safely collect and deduplicate non-nil error messages preserving order or unique set semantics.

### Proposed Changes
1. Implement `deduplicateErrors(errs []error) []string` in `adapters/v1/domain_to_syft.go`.
2. Add unit test coverage in `adapters/v1/domain_to_syft_test.go` verifying that nil errors are ignored and duplicate error messages are deduplicated properly.
```

### PR DESCRIPTION
**Pull request by NaitikRishu**
## Overview
Implements the missing `deduplicateErrors` helper in `adapters/v1/domain_to_syft.go` to resolve compiler and `go vet` failures when logging SBOM conversion warnings.

### Problem
In `adapters/v1/domain_to_syft.go:73`, `warnConversionErrors` calls `deduplicateErrors(errors)`. However, `deduplicateErrors` was never defined in the repository, causing `go vet ./...` and compilation of `adapters/v1` to fail with:
```text
adapters/v1/domain_to_syft.go:73:19: undefined: deduplicateErrors
```

### Changes
- Implemented `deduplicateErrors(errs []error) []string` in `domain_to_syft.go` to filter nil entries and return unique error strings while preserving insertion order.
- Added `Test_deduplicateErrors` and `Test_warnConversionErrors` in `domain_to_syft_test.go` covering empty, nil-filtering, and duplicate deduplication behaviors.

## How to Test
```bash
go test -v -run "Test_deduplicateErrors|Test_warnConversionErrors" ./adapters/v1/...
go vet ./...
go test ./...
```

## Related issues/PRs:
* Resolved #728

## Checklist before requesting a review
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my code
- [x] If it is a core feature, I have added thorough tests.
- [x] New and existing unit tests pass locally with my changes
```

<!-- This is an auto-generated comment: release notes by coderabbit.ai -->
## Summary by CodeRabbit

* **Bug Fixes**
  * Improved conversion warning handling by ignoring missing errors and reporting each distinct warning only once.
  * Preserved warning order and ensured warning processing does not affect converted relationship results.

* **Tests**
  * Expanded coverage for empty and missing errors, duplicate warnings, ordering, and unchanged conversion results.
<!-- end of auto-generated comment: release notes by coderabbit.ai -->

### CODE REVIEW

**Review by matthyx — DISMISSED** [review]
Reviewed. `deduplicateErrors` correctly filters nil errors and dedups messages while preserving insertion order, matching the call site in `warnConversionErrors` and resolving the `undefined: deduplicateErrors` compile/vet failure from #728. Added tests (`Test_deduplicateErrors`, `Test_warnConversionErrors`) cover empty, nil-filtering, and duplicate cases appropriately. All CI checks (build, lint, CodeQL, DCO, secrets) are green. No blockers — good to merge.

**Comment by matthyx** [comment]
⚠️ This PR now has a merge conflict with `main` (`mergeable_state: dirty`).

`main` already has a `deduplicateErrors` function defined in `adapters/v1/domain_to_syft.go` (landed via a separate fix after this PR was opened), so this branch's identical function name will collide/conflict on rebase. Note the two implementations also differ in behavior:

- `main`'s version: returns messages annotated with occurrence counts, e.g. `"%q occurred %d time(s)"`.
- this PR's version: returns plain deduplicated messages, first-seen order, no count annotation.

@NaitikRishu please rebase onto `main` and reconcile with the existing `deduplicateErrors` (either drop this PR's duplicate and keep main's, or update main's call sites/tests to match whichever behavior is intended) before this can merge.

**Comment by NaitikRishu** [comment]
> ⚠️ This PR now has a merge conflict with `main` (`mergeable_state: dirty`).
> 
> `main` already has a `deduplicateErrors` function defined in `adapters/v1/domain_to_syft.go` (landed via a separate fix after this PR was opened), so this branch's identical function name will collide/conflict on rebase. Note the two implementations also differ in behavior:
> 
> * `main`'s version: returns messages annotated with occurrence counts, e.g. `"%q occurred %d time(s)"`.
> * this PR's version: returns plain deduplicated messages, first-seen order, no count annotation.
> 
> @NaitikRishu please rebase onto `main` and reconcile with the existing `deduplicateErrors` (either drop this PR's duplicate and keep main's, or update main's call sites/tests to match whichever behavior is intended) before this can merge.

Rebased onto `main` and resolved merge conflicts with #730. Also added nil-safety to `deduplicateErrors` with matching unit tests. Ready for review!

**Review by matthyx — APPROVED** [review]
Conflict resolved — rebased onto `main` and reconciled with `main`'s existing `deduplicateErrors` (kept its count-annotated behavior, added the nil-safety check plus matching tests). Diff is now minimal and clean, no duplicate function, all CI checks (build, lint, CodeQL, DCO, secrets) are green. Good to merge.
